version: '3.6'
services:

  postgres-auth:
    container_name: auth_postgres
    image: postgres:14.5
    restart: always
    volumes:
      - db_data_auth:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    command: -p 5432
    ports:
      - '5432:5432'
    extra_hosts:
      - host.docker.internal:host-gateway

  graphql-engine-auth:
    container_name: auth_graphql
    image: hasura/graphql-engine:latest.cli-migrations-v3
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres-auth'
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    env_file:
      - docker.env
    extra_hosts:
      - host.docker.internal:host-gateway


volumes:
  db_data_auth:
