version: 3
endpoint: http://localhost:8080
admin_secret: hello-this-is-my-admin-secret
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
database_name: default